import axios from "axios";
import {
  GetStaticPaths,
  GetStaticProps,
  InferGetStaticPropsType,
  NextPage,
} from "next";
import Head from "next/head";

import {
  ProductImage,
  ProductInfo,
  ProductWrapper,
} from "../../components/index";

import { Product } from "../../types/interfaces";

const ProductDetails: NextPage = ({
  product,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>Product details</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      <div style={{ padding: "0 20px" }}>
        <h1>{product.title}</h1>
        <ProductWrapper>
          <ProductImage image={product.image} />
          <ProductInfo
            price={product.price}
            rating={product.rating.rate}
            description={product.description}
          />
        </ProductWrapper>
      </div>
    </div>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const { data } = await axios.get("https://fakestoreapi.com/products");
  const paths = data.map((product: Product) => ({
    params: { id: product.id?.toString() },
  }));
  return {
    paths,
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const { data } = await axios.get<Product>(
    `https://fakestoreapi.com/products/${params?.id}`
  );

  return {
    props: {
      product: data,
    },
    revalidate: 10,
  };
};

export default ProductDetails;
