import axios from "axios";
import {
  GetStaticPaths,
  GetStaticProps,
  InferGetStaticPropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";

import { Button } from "../../components/index";

import { Product } from "../../types/interfaces";

const ProductDetails: NextPage = ({
  product,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>Product details</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      <div>
        <h1>{product.title}</h1>
        <div
          className="flex-container"
          style={{ display: "flex", columnGap: "20px" }}
        >
          <div
            className="img-wrapper"
            style={{
              display: "block",
              flex: "1",
            }}
          >
            <Image
              src={product.image}
              width="400px"
              height="400px"
              layout="responsive"
              alt="product image"
            />
          </div>
          <div className="info" style={{ flex: "2" }}>
            <p style={{ fontSize: "32px", margin: 0 }}>{product.price}</p>
            <Button>Add to cart</Button>
            <p>
              rating: <span>{product.rating.rate}</span>
            </p>
            <p style={{ fontSize: "20px" }}>{product.description}</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const { data } = await axios.get("https://fakestoreapi.com/products");
  const paths = data.map((product: Product) => ({
    params: { id: product.id?.toString() },
  }));
  return {
    paths,
    fallback: "blocking",
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const { data } = await axios.get<Product>(
    `https://fakestoreapi.com/products/${params?.id}`
  );

  return {
    props: {
      product: data,
    },
    revalidate: 10,
  };
};

export default ProductDetails;
