import { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import axios from "axios";

import { Product } from "../types/interfaces";
import Products from "../components/products";

const Home: NextPage = ({
  data,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Products list={data} />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await axios.get<Product[]>(
    "https://fakestoreapi.com/products"
  );
  return {
    props: { data },
  };
};

export default Home;
